apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-xhed
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-xhed
    app.kubernetes.io/part-of: test-app-igaj
  name: test-component-xhed
  namespace: build-e2e-hacbs-uacv
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-xhed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-xhed
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:c19dfdb06b45433a8ebce0402a1375c6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
